<h2>Catálogo de Autos</h2>
<form method="POST" action="buscar">

   
    <label for="atributo">Buscar por:</label>
    <select id="atributo" name="atributo" required>
        <option value="marca">Marca</option>
        <option value="color">Color</option>
        <option value="kilometros">Kilómetros</option>
        <option value="asientos">Asientos</option>
        <option value="modelo">Modelo</option>
    </select>
    <label for="valor">Valor:</label>
    <input type="text" id="valor" name="valor" required>
    <button type="submit">Buscar</button>
</form>
</section>
</div>
