

<h2>Detalles del Auto</h2>

<table class="task-table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Color</th>
            <th>Modelo</th>
            <th>Kilómetros</th>
            <th>Asientos</th>
            <th>Marca</th>
            <th>Información Extra</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($detalles as $detalle) : ?>
            <tr>
                <td><?= $detalle->id ?></td>
                <td><?= $detalle->color ?></td>
                <td><?= $detalle->Modelo ?></td>
                <td><?= $detalle->kilometros ?></td>
                <td><?= $detalle->Asientos ?></td>
                <td><?= $detalle->marca ?></td>
                <td><?= $detalle->Informacion ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>


