

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Catalogo de autos</title>
    <link rel="stylesheet" href="<?= BASE_URL ?>css/css.css">

    
    
    
</head>
<body>
    
    <header>
        <h1>VENTA DE AUTOS</h1>
        <ul>
        <li><a href="<?= BASE_URL ?>">Página principal</a></li>
        <li><a href="<?= BASE_URL ?>MostrarLogin">Administración</a></li>


        </ul>
    </header>

    

    <div class="titulo"><h1>Nuestro catalogo completo</h1></div>
    
    
    

    

