<h2>Agregar Autos</h2>
<div class="form-container">
    <form action="agregar" method="POST"> 
        <label for="color">Color:</label>
        <input type="text" name="color" required>

        <label for="modelo">Modelo:</label>
        <input type="date" name="modelo" required> 

        <label for="kilometros">Kilometros:</label>
        <input type="text" name="kilometros" required>

        <label for="asientos">Asientos:</label>
        <input type="text" name="asientos" required>

        <label for="informacion">Informacion:</label>
        <input type="text" name="informacion" required>

        <label for="marca">Elija una de estas marcas:Ford,Tesla,Chevrolet,Renault </label>
        <input type="text" name="marca" required>

        <button type="submit">Agregar</button>
    </form>
</div>