<table class="task-table">
    <?php 
    if (!empty($catalogo)) {
        echo "<thead>
            <tr>
                <th>Color</th>
                <th>Modelo</th>
                <th>Kilómetros</th>
                <th>Asientos</th>
                <th>Marca</th>
                
            </tr>
        </thead>
        <tbody>";
        
        foreach ($catalogo as $detalle) {
            echo "<tr>
                <td>{$detalle->color}</td>
                <td>{$detalle->Modelo}</td>
                <td>{$detalle->kilometros}</td>
                <td>{$detalle->Asientos}</td>
                <td>{$detalle->marca}</td>
            </tr>";
        }
        echo "</tbody>";
    } else {
       
        echo "<tr>
            <td ><h1>No hay autos con esa característica</h1></td>
        </tr>";
    }
    ?>
</table>

